### ISSUE TITLE
JupyterLab Video Tutorials

### ISSUE THREAD

**Issue by van-8** [jupyterlab/jupyterlab-media#7]
@blink1073 Very very sorry, but I couldn't figure out how to create a pull request, as it asked for comparisons and branches other things I don't quite understand. Hope it's ok to just use an issue.

If needed, can be downloaded at this [Dropbox](https://www.dropbox.com/s/r7ij3wn0tpblr60/JuptyerLab%20How%20to%20use%20v1%20-%20HD%201080p.mov?dl=0) 

Thanks brother!!

**Comment by blink1073** [comment]
That'll work, thanks @van-8!

**Comment by blink1073** [comment]
Given the size of the video, I just went ahead and uploaded it to YouTube directly: https://youtu.be/A5YyoCKxEOU.  Thanks again!

**Comment by nickeubank** [comment]
@blink1073 @van-8 Hey, I was looking at the docs and was a little surprised to not see this this on the Overview page of the docs (sorry, can't comment in #6811 any more). There a reason this isn't hosted on jupyterlab's docs (or if it is, why it's hard to find)?

**Comment by blink1073** [comment]
Thanks for the prompt, @nickeubank!  I created https://github.com/jupyterlab/jupyterlab/pull/7804 to add it to the docs.

**Comment by jasongrout** [comment]
Thanks!
